import java.net.URI; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.UUID; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec;
public class BitSefClient {
 private final String baseUrl,secret; private final HttpClient http=HttpClient.newHttpClient();
 public BitSefClient(String u,String s){baseUrl=u.replaceAll("/$","");secret=s;}
 public String fiscalJson(String j)throws Exception{return post("/api/bitsef/fiscal",j,"application/json");} public String commandJson(String j)throws Exception{return post("/api/bitsef/command",j,"application/json");} public String copy(String n)throws Exception{return post("/api/bitsef/copy/"+n,"",null);} public String pdf(String n)throws Exception{return post("/api/bitsef/pdf/"+n,"",null);} public String directCsv(String t,String n,String c)throws Exception{return post("/api/bitsef/csv/"+t+"/"+n,c,"text/plain; charset=utf-8");}
 public String status(String id)throws Exception{return http.send(HttpRequest.newBuilder(URI.create(baseUrl+"/api/bitsef/status/"+id)).GET().build(),HttpResponse.BodyHandlers.ofString()).body();}
 private String post(String p,String b,String ct)throws Exception{String ts=Long.toString(Instant.now().getEpochSecond()),nonce=UUID.randomUUID().toString().replace("-","");String canonical="POST\n"+p+"\n"+ts+"\n"+nonce+"\n"+sha(b);HttpRequest.Builder x=HttpRequest.newBuilder(URI.create(baseUrl+p)).header("X-BIT-Timestamp",ts).header("X-BIT-Nonce",nonce).header("X-BIT-Signature",hmac(canonical));if(ct!=null)x.header("Content-Type",ct).POST(HttpRequest.BodyPublishers.ofString(b,StandardCharsets.UTF_8));else x.POST(HttpRequest.BodyPublishers.noBody());HttpResponse<String> r=http.send(x.build(),HttpResponse.BodyHandlers.ofString());if(r.statusCode()<200||r.statusCode()>=300)throw new RuntimeException("BIT-SEF HTTP "+r.statusCode()+": "+r.body());return r.body();}
 private static String hex(byte[] a){StringBuilder s=new StringBuilder();for(byte b:a)s.append(String.format("%02x",b));return s.toString();} private static String sha(String s)throws Exception{return hex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));} private String hmac(String s)throws Exception{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));return hex(m.doFinal(s.getBytes(StandardCharsets.UTF_8)));}
}
